baseURL = "https://turnitoffandonagain.github.io/Words/"
languageCode = "en-us"
title = "Graham Pople"
#theme = "beautifulhugo"
theme = "hyde"
publishDir = "docs"


pygmentsCodeFences = true
pygmentsUseClasses = true
[Params]
    UseChroma = true
    description = "Scala & Java Developer"
