baseURL = "https://gropple.github.io/Words"
#baseURL = "https://gropple.github.io/"
languageCode = "en-us"
title = "Graham Pople's site"
theme = "beautifulhugo"
publishDir = "docs"

pygmentsCodeFences = true
pygmentsUseClasses = true
[Params]
    UseChroma = true
