baseURL = "https://programmatix.github.io/Words/"
languageCode = "en-us"
title = "Graham Pople"
theme = "hyde"
publishDir = "docs"


pygmentsCodeFences = true
pygmentsUseClasses = true
[Params]
    UseChroma = true
    description = "Scala // Java // Web // C++ Developer"
